pub mod ticker_matcher;
pub mod news_aggregator;
pub mod portfolio_analyzer;
pub mod economic_calendar;
pub mod alert_escalator;
pub mod sentiment_analyzer;
pub mod market_data_stream;
pub mod alert_escalation_checker;
pub mod alert_channels;
pub mod alert_rule_engine;
pub mod embeddings;
pub mod api_key_manager;
pub mod market_cache;
pub mod rate_limiter;
pub mod price_alert_checker;
pub mod global_search;
pub mod desktop_notifications;
pub mod data_export;
pub mod script_engine;
pub mod workflow_engine;
pub mod workflow_scheduler;
pub mod automation_event_bus;
pub mod event_bridge;
pub mod command_dispatcher;
pub mod script_bridge;

pub use event_bridge::EventBridge;
pub use command_dispatcher::CommandDispatcher;
pub use script_bridge::ScriptBridgeServer;

pub use ticker_matcher::TickerMatcher;
pub use script_engine::{ScriptEngine, ScriptExecutionResult};
pub use workflow_engine::{WorkflowEngine, WorkflowStep, WorkflowContext};
pub use workflow_scheduler::WorkflowScheduler;
pub use automation_event_bus::{AutomationEventBus, AutomationEvent};
pub use desktop_notifications::{DesktopNotificationService, NotificationOptions};
pub use global_search::{GlobalSearchService, SearchResult, SearchSource};
pub use news_aggregator::NewsAggregator;
pub use portfolio_analyzer::{PortfolioAnalyzer, PortfolioValue, HoldingValue, ImpactAnalysis, HoldingImpact};
pub use economic_calendar::EconomicCalendarService;
pub use sentiment_analyzer::SentimentAnalyzer;

